services:
  mysql:
    image: mysql:8.4
    container_name: ecom-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecom_user
      MYSQL_PASSWORD: ecom_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uecom_user", "-pecom_pass"]
      interval: 5s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:3.7
    container_name: ecom-localstack
    restart: unless-stopped
    environment:
      SERVICES: s3
      DEBUG: "0"
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  mysql_data:
  localstack_data:
